### ISSUE TITLE
Incompatible with nodenv

### ISSUE THREAD

**Issue by raine** [dracupid/global-npm#4]
This module is incompatible with [`nodenv`](https://github.com/nodenv/nodenv). 

With nodenv, `npm` bin points to `$HOME/.nodenv/shims/npm`

```
/usr/local/lib/node_modules/ramda-cli/node_modules/global-npm/index.js:13
  throw err
  ^

Error: Cannot find module 'npm'
    at throwNotFoundError (/usr/local/lib/node_modules/ramda-cli/node_modules/global-npm/index.js:11:13)
    at /usr/local/lib/node_modules/ramda-cli/node_modules/global-npm/index.js:39:5
    at Object.<anonymous> (/usr/local/lib/node_modules/ramda-cli/node_modules/global-npm/index.js:41:3)
```

But there is at least one workaround.

```
# global-npm reads this
export GLOBAL_NPM_PATH="$HOME/.nodenv/versions/10.16.0/lib/node_modules/npm"
```

**Comment by dracupid** [comment]
Please try run `node -e "console.log(require('which').sync('npm'))" ` in your shell, and paste the result here.

I have tried nodenv on my mac and it works well with global-npm. Are you using a windows or Linux PC?

**Comment by dracupid** [comment]
Also please provide you PATH env. I will check this.

**Comment by raine** [comment]
Yes, I'm on a mac.

```
> console.log(require('which').sync('npm'))
/Users/raine/.nodenv/shims/npm
```

If you run this you should be able to reproduce the problem.

```sh
% npm install -g ramda-cli
% echo 1000 | ramda --import pretty-ms 'pretty-ms'
/usr/local/lib/node_modules/ramda-cli/node_modules/global-npm/index.js:13
  throw err
  ^

Error: Cannot find module 'npm'
```

```sh
% export GLOBAL_NPM_PATH="$HOME/.nodenv/versions/10.16.0/lib/node_modules/npm"
% echo 1000 | ramda --import pretty-ms 'pretty-ms'
+ pretty-ms@5.0.0
added 3 packages from 1 contributor, removed 1 package and audited 11 packages in 1.271s
found 0 vulnerabilities
"1s"
```

**Comment by dracupid** [comment]
I find that nodenv will prepend PATH env with real npm path. (see https://github.com/nodenv/nodenv/blob/master/libexec/nodenv-exec#L44)

I guess you are using a system node(NODENV_VERSION == 'system'). I can reproduce the issue with `nodenv local system` 😆

If so, I will try to fix it.

**Comment by dracupid** [comment]
try 0.4.0
