### ISSUE TITLE
Globally installed NPM version 8 causes "Cannot find module 'npm'"

### ISSUE THREAD

**Issue by RappC** [dracupid/global-npm#7]
This is due to a missing `index.js` file within `npm` being referenced in its `package,json` `main` property.

Tested with npm installed via linux homebrew.

When running the tests included in this project with npm 8 the tests fail with
`Error: The programmatic API was removed in npm v8.0.0`

**Comment by dracupid** [comment]
This issue is casued by a breaking change of npm@8, https://github.com/npm/cli/pull/3762.
I have tried to make global-npm work under npm@8, but it seems that programmatic api via require('npm') may be no longer supported.
